### ISSUE TITLE
How to use Tags

### ISSUE THREAD

**Issue by tyeeman** [FooSoft/goldsmith#3]
Thanks for that last update about slashes, working good now. I can't seem to locate any blog post samples using Tags. Could you add a quick summary. I tried adding
```
Tags = "One, Two"
```
in a post.md but nothing seems to happen when I restart Goldsmith.

**Comment by tyeeman** [comment]
OK, I found the syntax for Tags in the projects/widget/index.md file. The tags now show in the blog post, but how to get the tags showing on the main index page? Also, what is the syntax for adding the date in a post just like on your site?

**Comment by FooSoft** [comment]
It depends on how you choose to set up your metadata. I use TOML, so the I just specify dates in the format that it expects dates to be in. For example, [this page](https://foosoft.net/posts/working-with-patches-in-git/) has the following metadata:

```
+++
Date = 2022-06-12
Summary = "Generating and applying branch-agnostic patches for debug code in git."
Tags = ["git", "guide"]
+++
```

There is nothing special about the name "Date". I could have easily called it "Foo"; it just matters what plugins process this data (nothing needs to process dates), and what templates consume this metadata. 

Regarding tags, there are two types of information. A [global list of tags](https://github.com/FooSoft/goldsmith-samples/blob/727dc8926eaf923cfb837b01e12e1907ee708fe5/bootstrap/content/layouts/content.gohtml#L36), as well as the [tags for the current page](https://github.com/FooSoft/goldsmith-samples/blob/727dc8926eaf923cfb837b01e12e1907ee708fe5/bootstrap/content/layouts/cloud.gohtml). I'm not sure which you are referring to here.

You decide what information gets displayed where.

**Comment by tyeeman** [comment]
OK, thanks. Here is an image from your site. The two circled items are what I would like on my site. Just trying to determine what code I need to make the tags and date appear on the listing of all posts index page. I am getting the tags showing on my individual posts, it's just the main index listing where I would like them also. It's obviously a layout template I need to add to. The main index.md file says it uses the "Collection" layout. See below code showing where I think I need to add code.

<img width="590" alt="2022-10-19_181424" src="https://user-images.githubusercontent.com/4469306/196833535-353030c2-b1de-4141-9b3f-729b3c88a47e.png">

collection.gohtml
```
{{define "collection"}}
{{template "header" .}}
<div class="container">
    {{range .Props.Groups.Blog}}
    <div>
        <h2><a href="{{.Path}}">{{.Props.Title}}</a></h2>
	Do I add something here to make the tags appear?
        <p>
            {{.Props.Summary}}
            <a href="{{.Path}}">&hellip;</a>
        </p>
    </div>
    {{end}}
</div>
	{{template "footer" .}}
{{end}}
```

**Comment by tyeeman** [comment]
Update - Yes, where I said I should add code I did add ``` {{template "cloud" .}}``` and now the tags show up on the main page. I'll work on getting the date there too.

Update - Adding date is ```{{.Props.Date}}```

Thanks for the tips!

**Comment by FooSoft** [comment]
I've long ago diverged from the Bootstrap template to a completely custom style for foosoft.net, but this may help illustrate how that component works:

```
{{define "story-list-item"}}
<div class="story-date">
    {{.Props.Date.Format "Jan 2, 2006"}}
</div>
<div class="story-summary">
    <h2><a href="/{{.Dir}}">{{.Props.Title}}</a></h2>
    {{template "tag-list" .}}
    <p>{{.Props.Summary}}</p>
</div>
{{end}}

{{define "story-list"}}
<div class="story-list">
    {{range .}}{{template "story-list-item" .}}{{end}}
</div>
{{end}}

{{define "posts"}}
{{template "header" .}}

{{.Props.Content}}
{{template "story-list" .Props.Groups.posts}}

{{template "footer" .}}
{{end}}
```

**Comment by tyeeman** [comment]
Yes, that looks maybe more effcient than the Bootstrap templates. I will try it. Thanks for that. 

I guess I can create only one .gohtml file with everything defined in it, yes?

I have entered my own template into outer.gohtml as header and footer and it's working fine. I guess these .gohtml files can have any name I want because they are all read at once.

One last question, if I want to create just an exe to build my site without running the server and not use the cache files what do I need to delete in main.go? I tried deleting the following line -
```
devserver.DevServe(new(builder), *port, "content", "build", "cache")
```
but I got an errors about declared but not used.

So is the cache necessary for my site to work on an online static server or is it just used locally here when running the server?

**Comment by FooSoft** [comment]
You can use as few or as many gohtml template files as you need. They are just there to help you keep your stuff organized.

The cache only exists to locally speed up site generation. Currently, my entire site rebuilds from scratch in about 100ms, so you may not need it. I mostly added it for the use case where you have an image gallery and must create thousands of thumbnails. The cache would allow results from a previous build to be reused. Once the static site is build, it is of no relevance.

If you don't want to run a server, just call `Build` directly on the `builder` instance you are currently passing into `devserver.DevServe`.

So basically just use this:
```go
func (self *builder) Build(contentDir, buildDir, cacheDir string) {
	tagMeta := map[string]interface{}{
		"Area":        "tags",
		"CrumbParent": "tags",
		"Layout":      "tag",
	}

	indexMeta := map[string]interface{}{
		"Layout": "index",
	}

	errs := goldsmith.Begin(contentDir).
		Cache(cacheDir).
		Chain(frontmatter.New()).
		Chain(markdown.New()).
		Chain(summary.New()).
		Chain(collection.New()).
		Chain(index.New(indexMeta)).
		Chain(tags.New().IndexMeta(tagMeta)).
		Chain(breadcrumbs.New()).
		Chain(layout.New()).
		Chain(syntax.New().Placement(syntax.PlaceInline)).
		Chain(document.New(fixup)).
		Chain(thumbnail.New()).
		Chain(absolute.New()).
		End(buildDir)

	for _, err := range errs {
		log.Print(err)
	}
}
```

Again, feel free to skip the cache. You most likely won't need it.
